/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JERVIS;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Mateusz
 */
public class helpGUI extends javax.swing.JFrame {

    /**
     * Creates new form helpGUI
     * @throws java.io.IOException
     */
    public helpGUI() throws IOException {
        initComponents();
        setIconImage(ImageIO.read(new File("img/JervisMiniBG.png")));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(777, 600));
        setMinimumSize(new java.awt.Dimension(777, 600));
        setName("help"); // NOI18N
        setPreferredSize(new java.awt.Dimension(777, 600));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText(" \t\t\t*** Help ***\n\n NOTE: When the application is opened, you need to wait for Jervis to say: \"I am ready to serve you sir!\"\n\n \"Jervis\" - gives the assistant's attention (must be used before other commands)\n\n - \"You can go\"/\"go away\" - the application exits.\n\n - \"Good morning/afternoon/evening\"/\"Hello\"/\"how are you?\" - initiates conversation with Jervis\n    the answer to his question: \"What about yourself, sir\", should be optimally one word i.e. \"excellent\"\n \n - \"Remeber my location/name/email/sex/profession\" - changing the information Jervis remebers about the user\n \n - \"What is/what's my location/name/email/sex/profession\" - retreiving the information Jervis remebers about the user\n    the user.\n \n - \"What is/what's your name\" - query for Jervis's name.\n \n - \"What is/what's the weather *in my location\" - Retrivies weather forecast.\n \n - \"What is/what's the date\" - Retrivies current local date.\n\n - \"What is/what's the time\" - Retrivies current local time.\n \n - \"What is/what's my schedule\" - Retreives schedule for current date.\n \n - \"Set nem commands\" - opens the custom command dialog.\n \n - \"Set a/an* event/meeting/appointment/event/meeting/appointment\" - Jervis will schedule an event.\n\n - \"Open a/an* website/location\" - Jervis opens a given website or location.\n\n - \"Make a* research\" - Jervis makes a research on given definition.\n\n - \"Make a* note\" - Jervis produces a .txt file of a given length:\n     SHORT:  5s\n     MEDIUM: 10s\n     LONG:   15s\n - \"Thank you\" - thank Jervis for the excellent service :) \n\n \n - \"Translate\" [ALPHA tests !!!] - allows to translate from English to French. Currently, Jervis \n     is not really good with reading French.\n\nLegend:\n* = optional\n/ = or\n \n\n\n© Mateusz Michalski aka Nytorian\n");
        jTextArea1.setToolTipText("Help for Jervis");
        jTextArea1.setFocusable(false);
        jTextArea1.setPreferredSize(new java.awt.Dimension(900, 900));
        jTextArea1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(helpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(helpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(helpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(helpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new helpGUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(helpGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
