/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JERVIS;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Mateusz
 */
public class mainGUI extends javax.swing.JFrame {

    /**
     * Creates new form mainGUI
     * @throws java.io.IOException
     */
    public mainGUI() throws IOException {
        initComponents();
        setIconImage(ImageIO.read(new File("img/JervisMiniBG.png")));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        lblAnim = new javax.swing.JLabel();
        chkListen = new javax.swing.JCheckBox();
        btnCustomCmd = new javax.swing.JButton();
        btnFavWeb = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("J.E.R.V.I.S");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\J.E.R.V.I.S\\J.E.R.V.I.S\\GitHub\\img\\JervisBG.jpg")); // NOI18N
        jLabel1.setToolTipText("main dialog");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 780);

        lblAnim.setIcon(new javax.swing.ImageIcon("D:\\J.E.R.V.I.S\\J.E.R.V.I.S\\GitHub\\img\\Voice Animation\\s0.jpg")); // NOI18N
        jLayeredPane1.setLayer(lblAnim, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(lblAnim);
        lblAnim.setBounds(400, 410, 200, 100);

        chkListen.setBackground(new java.awt.Color(153, 204, 255));
        chkListen.setFont(new java.awt.Font("Prestige Elite Std", 1, 14)); // NOI18N
        chkListen.setSelected(true);
        chkListen.setText("Linstening?");
        chkListen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkListenActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(chkListen, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(chkListen);
        chkListen.setBounds(140, 550, 120, 25);

        btnCustomCmd.setBackground(new java.awt.Color(0, 0, 0));
        btnCustomCmd.setFont(new java.awt.Font("Prestige Elite Std", 1, 14)); // NOI18N
        btnCustomCmd.setText("Custom Commands");
        btnCustomCmd.setBorderPainted(false);
        btnCustomCmd.setContentAreaFilled(false);
        btnCustomCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomCmdActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(btnCustomCmd, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(btnCustomCmd);
        btnCustomCmd.setBounds(100, 230, 170, 23);

        btnFavWeb.setFont(new java.awt.Font("Prestige Elite Std", 1, 14)); // NOI18N
        btnFavWeb.setText("Weather Places");
        btnFavWeb.setBorderPainted(false);
        btnFavWeb.setContentAreaFilled(false);
        btnFavWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavWebActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(btnFavWeb, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(btnFavWeb);
        btnFavWeb.setBounds(170, 130, 190, 23);

        jButton1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButton1.setText("[ ? ]");
        jButton1.setToolTipText("Opens help dialog");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(630, 120, 79, 25);
        jButton1.getAccessibleContext().setAccessibleName("help");
        jButton1.getAccessibleContext().setAccessibleDescription("help");

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(-1, 0, 1000, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkListenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkListenActionPerformed
        Jervis.setListening(!Jervis.bListening);
    }//GEN-LAST:event_chkListenActionPerformed

    private void btnCustomCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomCmdActionPerformed
        try {
            commandGUI cmdGUI = new commandGUI();
        } catch (IOException ex) {
            Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCustomCmdActionPerformed

    private void btnFavWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavWebActionPerformed
        try {
            weatherGUI weatherGUI = new weatherGUI();
        } catch (IOException ex) {
            Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFavWebActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            helpGUI helpGUI = new helpGUI();
        } catch (IOException ex) {
            Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomCmd;
    private javax.swing.JButton btnFavWeb;
    public static javax.swing.JCheckBox chkListen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    public static javax.swing.JLabel lblAnim;
    // End of variables declaration//GEN-END:variables
}
