// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomCmd.proto

package TextBase;

public final class CustomCmd {
  private CustomCmd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CustomCmd.Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string Cmd = 1;</code>
     */
    com.google.protobuf.ProtocolStringList
        getCmdList();
    /**
     * <code>repeated string Cmd = 1;</code>
     */
    int getCmdCount();
    /**
     * <code>repeated string Cmd = 1;</code>
     */
    java.lang.String getCmd(int index);
    /**
     * <code>repeated string Cmd = 1;</code>
     */
    com.google.protobuf.ByteString
        getCmdBytes(int index);

    /**
     * <code>repeated string Dir = 2;</code>
     */
    com.google.protobuf.ProtocolStringList
        getDirList();
    /**
     * <code>repeated string Dir = 2;</code>
     */
    int getDirCount();
    /**
     * <code>repeated string Dir = 2;</code>
     */
    java.lang.String getDir(int index);
    /**
     * <code>repeated string Dir = 2;</code>
     */
    com.google.protobuf.ByteString
        getDirBytes(int index);
  }
  /**
   * Protobuf type {@code CustomCmd.Command}
   */
  public static final class Command extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CustomCmd.Command)
      CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Command(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }

    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                cmd_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              cmd_.add(bs);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                dir_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              dir_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          cmd_ = cmd_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          dir_ = dir_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TextBase.CustomCmd.internal_static_CustomCmd_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TextBase.CustomCmd.internal_static_CustomCmd_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TextBase.CustomCmd.Command.class, TextBase.CustomCmd.Command.Builder.class);
    }

    public static com.google.protobuf.Parser<Command> PARSER =
        new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList cmd_;
    /**
     * <code>repeated string Cmd = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCmdList() {
      return cmd_;
    }
    /**
     * <code>repeated string Cmd = 1;</code>
     */
    public int getCmdCount() {
      return cmd_.size();
    }
    /**
     * <code>repeated string Cmd = 1;</code>
     */
    public java.lang.String getCmd(int index) {
      return cmd_.get(index);
    }
    /**
     * <code>repeated string Cmd = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCmdBytes(int index) {
      return cmd_.getByteString(index);
    }

    public static final int DIR_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList dir_;
    /**
     * <code>repeated string Dir = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDirList() {
      return dir_;
    }
    /**
     * <code>repeated string Dir = 2;</code>
     */
    public int getDirCount() {
      return dir_.size();
    }
    /**
     * <code>repeated string Dir = 2;</code>
     */
    public java.lang.String getDir(int index) {
      return dir_.get(index);
    }
    /**
     * <code>repeated string Dir = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDirBytes(int index) {
      return dir_.getByteString(index);
    }

    private void initFields() {
      cmd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      dir_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < cmd_.size(); i++) {
        output.writeBytes(1, cmd_.getByteString(i));
      }
      for (int i = 0; i < dir_.size(); i++) {
        output.writeBytes(2, dir_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < cmd_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(cmd_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCmdList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dir_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(dir_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getDirList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TextBase.CustomCmd.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TextBase.CustomCmd.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TextBase.CustomCmd.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TextBase.CustomCmd.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TextBase.CustomCmd.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TextBase.CustomCmd.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TextBase.CustomCmd.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TextBase.CustomCmd.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TextBase.CustomCmd.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TextBase.CustomCmd.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TextBase.CustomCmd.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CustomCmd.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CustomCmd.Command)
        TextBase.CustomCmd.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TextBase.CustomCmd.internal_static_CustomCmd_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TextBase.CustomCmd.internal_static_CustomCmd_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TextBase.CustomCmd.Command.class, TextBase.CustomCmd.Command.Builder.class);
      }

      // Construct using TextBase.CustomCmd.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        dir_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TextBase.CustomCmd.internal_static_CustomCmd_Command_descriptor;
      }

      public TextBase.CustomCmd.Command getDefaultInstanceForType() {
        return TextBase.CustomCmd.Command.getDefaultInstance();
      }

      public TextBase.CustomCmd.Command build() {
        TextBase.CustomCmd.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TextBase.CustomCmd.Command buildPartial() {
        TextBase.CustomCmd.Command result = new TextBase.CustomCmd.Command(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          cmd_ = cmd_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cmd_ = cmd_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          dir_ = dir_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.dir_ = dir_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TextBase.CustomCmd.Command) {
          return mergeFrom((TextBase.CustomCmd.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TextBase.CustomCmd.Command other) {
        if (other == TextBase.CustomCmd.Command.getDefaultInstance()) return this;
        if (!other.cmd_.isEmpty()) {
          if (cmd_.isEmpty()) {
            cmd_ = other.cmd_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCmdIsMutable();
            cmd_.addAll(other.cmd_);
          }
          onChanged();
        }
        if (!other.dir_.isEmpty()) {
          if (dir_.isEmpty()) {
            dir_ = other.dir_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDirIsMutable();
            dir_.addAll(other.dir_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TextBase.CustomCmd.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TextBase.CustomCmd.Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList cmd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCmdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          cmd_ = new com.google.protobuf.LazyStringArrayList(cmd_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string Cmd = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getCmdList() {
        return cmd_.getUnmodifiableView();
      }
      /**
       * <code>repeated string Cmd = 1;</code>
       */
      public int getCmdCount() {
        return cmd_.size();
      }
      /**
       * <code>repeated string Cmd = 1;</code>
       */
      public java.lang.String getCmd(int index) {
        return cmd_.get(index);
      }
      /**
       * <code>repeated string Cmd = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCmdBytes(int index) {
        return cmd_.getByteString(index);
      }
      /**
       * <code>repeated string Cmd = 1;</code>
       */
      public Builder setCmd(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCmdIsMutable();
        cmd_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Cmd = 1;</code>
       */
      public Builder addCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCmdIsMutable();
        cmd_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Cmd = 1;</code>
       */
      public Builder addAllCmd(
          java.lang.Iterable<java.lang.String> values) {
        ensureCmdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cmd_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Cmd = 1;</code>
       */
      public Builder clearCmd() {
        cmd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Cmd = 1;</code>
       */
      public Builder addCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCmdIsMutable();
        cmd_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList dir_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDirIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          dir_ = new com.google.protobuf.LazyStringArrayList(dir_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string Dir = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDirList() {
        return dir_.getUnmodifiableView();
      }
      /**
       * <code>repeated string Dir = 2;</code>
       */
      public int getDirCount() {
        return dir_.size();
      }
      /**
       * <code>repeated string Dir = 2;</code>
       */
      public java.lang.String getDir(int index) {
        return dir_.get(index);
      }
      /**
       * <code>repeated string Dir = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDirBytes(int index) {
        return dir_.getByteString(index);
      }
      /**
       * <code>repeated string Dir = 2;</code>
       */
      public Builder setDir(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDirIsMutable();
        dir_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Dir = 2;</code>
       */
      public Builder addDir(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDirIsMutable();
        dir_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Dir = 2;</code>
       */
      public Builder addAllDir(
          java.lang.Iterable<java.lang.String> values) {
        ensureDirIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dir_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Dir = 2;</code>
       */
      public Builder clearDir() {
        dir_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Dir = 2;</code>
       */
      public Builder addDirBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDirIsMutable();
        dir_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CustomCmd.Command)
    }

    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CustomCmd.Command)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomCmd_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CustomCmd_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CustomCmd.proto\022\tCustomCmd\"#\n\007Command\022" +
      "\013\n\003Cmd\030\001 \003(\t\022\013\n\003Dir\030\002 \003(\tB\025\n\010TextBaseB\tC" +
      "ustomCmd"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CustomCmd_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CustomCmd_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CustomCmd_Command_descriptor,
        new java.lang.String[] { "Cmd", "Dir", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
