// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Organiser.proto

package TextBase;

public final class Organiser {
  private Organiser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Organiser.Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string title = 1;</code>
     */
    com.google.protobuf.ProtocolStringList
        getTitleList();
    /**
     * <code>repeated string title = 1;</code>
     */
    int getTitleCount();
    /**
     * <code>repeated string title = 1;</code>
     */
    java.lang.String getTitle(int index);
    /**
     * <code>repeated string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes(int index);

    /**
     * <code>repeated string dayMonth = 2;</code>
     */
    com.google.protobuf.ProtocolStringList
        getDayMonthList();
    /**
     * <code>repeated string dayMonth = 2;</code>
     */
    int getDayMonthCount();
    /**
     * <code>repeated string dayMonth = 2;</code>
     */
    java.lang.String getDayMonth(int index);
    /**
     * <code>repeated string dayMonth = 2;</code>
     */
    com.google.protobuf.ByteString
        getDayMonthBytes(int index);

    /**
     * <code>repeated string year = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getYearList();
    /**
     * <code>repeated string year = 3;</code>
     */
    int getYearCount();
    /**
     * <code>repeated string year = 3;</code>
     */
    java.lang.String getYear(int index);
    /**
     * <code>repeated string year = 3;</code>
     */
    com.google.protobuf.ByteString
        getYearBytes(int index);

    /**
     * <code>repeated string time = 4;</code>
     */
    com.google.protobuf.ProtocolStringList
        getTimeList();
    /**
     * <code>repeated string time = 4;</code>
     */
    int getTimeCount();
    /**
     * <code>repeated string time = 4;</code>
     */
    java.lang.String getTime(int index);
    /**
     * <code>repeated string time = 4;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes(int index);

    /**
     * <code>repeated string timeToRemind = 5;</code>
     */
    com.google.protobuf.ProtocolStringList
        getTimeToRemindList();
    /**
     * <code>repeated string timeToRemind = 5;</code>
     */
    int getTimeToRemindCount();
    /**
     * <code>repeated string timeToRemind = 5;</code>
     */
    java.lang.String getTimeToRemind(int index);
    /**
     * <code>repeated string timeToRemind = 5;</code>
     */
    com.google.protobuf.ByteString
        getTimeToRemindBytes(int index);
  }
  /**
   * Protobuf type {@code Organiser.Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Organiser.Event)
      EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Event(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }

    public Event getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                title_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              title_.add(bs);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                dayMonth_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              dayMonth_.add(bs);
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                year_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              year_.add(bs);
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                time_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              time_.add(bs);
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                timeToRemind_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              timeToRemind_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          title_ = title_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          dayMonth_ = dayMonth_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          year_ = year_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          time_ = time_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          timeToRemind_ = timeToRemind_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TextBase.Organiser.internal_static_Organiser_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TextBase.Organiser.internal_static_Organiser_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TextBase.Organiser.Event.class, TextBase.Organiser.Event.Builder.class);
    }

    public static com.google.protobuf.Parser<Event> PARSER =
        new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    public static final int TITLE_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList title_;
    /**
     * <code>repeated string title = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTitleList() {
      return title_;
    }
    /**
     * <code>repeated string title = 1;</code>
     */
    public int getTitleCount() {
      return title_.size();
    }
    /**
     * <code>repeated string title = 1;</code>
     */
    public java.lang.String getTitle(int index) {
      return title_.get(index);
    }
    /**
     * <code>repeated string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes(int index) {
      return title_.getByteString(index);
    }

    public static final int DAYMONTH_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList dayMonth_;
    /**
     * <code>repeated string dayMonth = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDayMonthList() {
      return dayMonth_;
    }
    /**
     * <code>repeated string dayMonth = 2;</code>
     */
    public int getDayMonthCount() {
      return dayMonth_.size();
    }
    /**
     * <code>repeated string dayMonth = 2;</code>
     */
    public java.lang.String getDayMonth(int index) {
      return dayMonth_.get(index);
    }
    /**
     * <code>repeated string dayMonth = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDayMonthBytes(int index) {
      return dayMonth_.getByteString(index);
    }

    public static final int YEAR_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList year_;
    /**
     * <code>repeated string year = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getYearList() {
      return year_;
    }
    /**
     * <code>repeated string year = 3;</code>
     */
    public int getYearCount() {
      return year_.size();
    }
    /**
     * <code>repeated string year = 3;</code>
     */
    public java.lang.String getYear(int index) {
      return year_.get(index);
    }
    /**
     * <code>repeated string year = 3;</code>
     */
    public com.google.protobuf.ByteString
        getYearBytes(int index) {
      return year_.getByteString(index);
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList time_;
    /**
     * <code>repeated string time = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTimeList() {
      return time_;
    }
    /**
     * <code>repeated string time = 4;</code>
     */
    public int getTimeCount() {
      return time_.size();
    }
    /**
     * <code>repeated string time = 4;</code>
     */
    public java.lang.String getTime(int index) {
      return time_.get(index);
    }
    /**
     * <code>repeated string time = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes(int index) {
      return time_.getByteString(index);
    }

    public static final int TIMETOREMIND_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList timeToRemind_;
    /**
     * <code>repeated string timeToRemind = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTimeToRemindList() {
      return timeToRemind_;
    }
    /**
     * <code>repeated string timeToRemind = 5;</code>
     */
    public int getTimeToRemindCount() {
      return timeToRemind_.size();
    }
    /**
     * <code>repeated string timeToRemind = 5;</code>
     */
    public java.lang.String getTimeToRemind(int index) {
      return timeToRemind_.get(index);
    }
    /**
     * <code>repeated string timeToRemind = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTimeToRemindBytes(int index) {
      return timeToRemind_.getByteString(index);
    }

    private void initFields() {
      title_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      dayMonth_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      year_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      time_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      timeToRemind_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < title_.size(); i++) {
        output.writeBytes(1, title_.getByteString(i));
      }
      for (int i = 0; i < dayMonth_.size(); i++) {
        output.writeBytes(2, dayMonth_.getByteString(i));
      }
      for (int i = 0; i < year_.size(); i++) {
        output.writeBytes(3, year_.getByteString(i));
      }
      for (int i = 0; i < time_.size(); i++) {
        output.writeBytes(4, time_.getByteString(i));
      }
      for (int i = 0; i < timeToRemind_.size(); i++) {
        output.writeBytes(5, timeToRemind_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < title_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(title_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTitleList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dayMonth_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(dayMonth_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getDayMonthList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < year_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(year_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getYearList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < time_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(time_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTimeList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < timeToRemind_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(timeToRemind_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTimeToRemindList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TextBase.Organiser.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TextBase.Organiser.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TextBase.Organiser.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TextBase.Organiser.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TextBase.Organiser.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TextBase.Organiser.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TextBase.Organiser.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TextBase.Organiser.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TextBase.Organiser.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TextBase.Organiser.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TextBase.Organiser.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Organiser.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Organiser.Event)
        TextBase.Organiser.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TextBase.Organiser.internal_static_Organiser_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TextBase.Organiser.internal_static_Organiser_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TextBase.Organiser.Event.class, TextBase.Organiser.Event.Builder.class);
      }

      // Construct using TextBase.Organiser.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        title_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        dayMonth_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        year_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        timeToRemind_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TextBase.Organiser.internal_static_Organiser_Event_descriptor;
      }

      public TextBase.Organiser.Event getDefaultInstanceForType() {
        return TextBase.Organiser.Event.getDefaultInstance();
      }

      public TextBase.Organiser.Event build() {
        TextBase.Organiser.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TextBase.Organiser.Event buildPartial() {
        TextBase.Organiser.Event result = new TextBase.Organiser.Event(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          title_ = title_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.title_ = title_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          dayMonth_ = dayMonth_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.dayMonth_ = dayMonth_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          year_ = year_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.year_ = year_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          time_ = time_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.time_ = time_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          timeToRemind_ = timeToRemind_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.timeToRemind_ = timeToRemind_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TextBase.Organiser.Event) {
          return mergeFrom((TextBase.Organiser.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TextBase.Organiser.Event other) {
        if (other == TextBase.Organiser.Event.getDefaultInstance()) return this;
        if (!other.title_.isEmpty()) {
          if (title_.isEmpty()) {
            title_ = other.title_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTitleIsMutable();
            title_.addAll(other.title_);
          }
          onChanged();
        }
        if (!other.dayMonth_.isEmpty()) {
          if (dayMonth_.isEmpty()) {
            dayMonth_ = other.dayMonth_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDayMonthIsMutable();
            dayMonth_.addAll(other.dayMonth_);
          }
          onChanged();
        }
        if (!other.year_.isEmpty()) {
          if (year_.isEmpty()) {
            year_ = other.year_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureYearIsMutable();
            year_.addAll(other.year_);
          }
          onChanged();
        }
        if (!other.time_.isEmpty()) {
          if (time_.isEmpty()) {
            time_ = other.time_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTimeIsMutable();
            time_.addAll(other.time_);
          }
          onChanged();
        }
        if (!other.timeToRemind_.isEmpty()) {
          if (timeToRemind_.isEmpty()) {
            timeToRemind_ = other.timeToRemind_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureTimeToRemindIsMutable();
            timeToRemind_.addAll(other.timeToRemind_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TextBase.Organiser.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TextBase.Organiser.Event) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList title_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTitleIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          title_ = new com.google.protobuf.LazyStringArrayList(title_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string title = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTitleList() {
        return title_.getUnmodifiableView();
      }
      /**
       * <code>repeated string title = 1;</code>
       */
      public int getTitleCount() {
        return title_.size();
      }
      /**
       * <code>repeated string title = 1;</code>
       */
      public java.lang.String getTitle(int index) {
        return title_.get(index);
      }
      /**
       * <code>repeated string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes(int index) {
        return title_.getByteString(index);
      }
      /**
       * <code>repeated string title = 1;</code>
       */
      public Builder setTitle(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTitleIsMutable();
        title_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string title = 1;</code>
       */
      public Builder addTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTitleIsMutable();
        title_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string title = 1;</code>
       */
      public Builder addAllTitle(
          java.lang.Iterable<java.lang.String> values) {
        ensureTitleIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, title_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string title = 1;</code>
       */
      public Builder clearTitle() {
        title_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string title = 1;</code>
       */
      public Builder addTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTitleIsMutable();
        title_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList dayMonth_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDayMonthIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          dayMonth_ = new com.google.protobuf.LazyStringArrayList(dayMonth_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string dayMonth = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDayMonthList() {
        return dayMonth_.getUnmodifiableView();
      }
      /**
       * <code>repeated string dayMonth = 2;</code>
       */
      public int getDayMonthCount() {
        return dayMonth_.size();
      }
      /**
       * <code>repeated string dayMonth = 2;</code>
       */
      public java.lang.String getDayMonth(int index) {
        return dayMonth_.get(index);
      }
      /**
       * <code>repeated string dayMonth = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDayMonthBytes(int index) {
        return dayMonth_.getByteString(index);
      }
      /**
       * <code>repeated string dayMonth = 2;</code>
       */
      public Builder setDayMonth(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDayMonthIsMutable();
        dayMonth_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dayMonth = 2;</code>
       */
      public Builder addDayMonth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDayMonthIsMutable();
        dayMonth_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dayMonth = 2;</code>
       */
      public Builder addAllDayMonth(
          java.lang.Iterable<java.lang.String> values) {
        ensureDayMonthIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dayMonth_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dayMonth = 2;</code>
       */
      public Builder clearDayMonth() {
        dayMonth_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dayMonth = 2;</code>
       */
      public Builder addDayMonthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDayMonthIsMutable();
        dayMonth_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList year_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureYearIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          year_ = new com.google.protobuf.LazyStringArrayList(year_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string year = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getYearList() {
        return year_.getUnmodifiableView();
      }
      /**
       * <code>repeated string year = 3;</code>
       */
      public int getYearCount() {
        return year_.size();
      }
      /**
       * <code>repeated string year = 3;</code>
       */
      public java.lang.String getYear(int index) {
        return year_.get(index);
      }
      /**
       * <code>repeated string year = 3;</code>
       */
      public com.google.protobuf.ByteString
          getYearBytes(int index) {
        return year_.getByteString(index);
      }
      /**
       * <code>repeated string year = 3;</code>
       */
      public Builder setYear(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureYearIsMutable();
        year_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string year = 3;</code>
       */
      public Builder addYear(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureYearIsMutable();
        year_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string year = 3;</code>
       */
      public Builder addAllYear(
          java.lang.Iterable<java.lang.String> values) {
        ensureYearIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, year_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string year = 3;</code>
       */
      public Builder clearYear() {
        year_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string year = 3;</code>
       */
      public Builder addYearBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureYearIsMutable();
        year_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList time_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTimeIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          time_ = new com.google.protobuf.LazyStringArrayList(time_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string time = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTimeList() {
        return time_.getUnmodifiableView();
      }
      /**
       * <code>repeated string time = 4;</code>
       */
      public int getTimeCount() {
        return time_.size();
      }
      /**
       * <code>repeated string time = 4;</code>
       */
      public java.lang.String getTime(int index) {
        return time_.get(index);
      }
      /**
       * <code>repeated string time = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes(int index) {
        return time_.getByteString(index);
      }
      /**
       * <code>repeated string time = 4;</code>
       */
      public Builder setTime(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTimeIsMutable();
        time_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string time = 4;</code>
       */
      public Builder addTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTimeIsMutable();
        time_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string time = 4;</code>
       */
      public Builder addAllTime(
          java.lang.Iterable<java.lang.String> values) {
        ensureTimeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, time_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string time = 4;</code>
       */
      public Builder clearTime() {
        time_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string time = 4;</code>
       */
      public Builder addTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTimeIsMutable();
        time_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList timeToRemind_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTimeToRemindIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          timeToRemind_ = new com.google.protobuf.LazyStringArrayList(timeToRemind_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string timeToRemind = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTimeToRemindList() {
        return timeToRemind_.getUnmodifiableView();
      }
      /**
       * <code>repeated string timeToRemind = 5;</code>
       */
      public int getTimeToRemindCount() {
        return timeToRemind_.size();
      }
      /**
       * <code>repeated string timeToRemind = 5;</code>
       */
      public java.lang.String getTimeToRemind(int index) {
        return timeToRemind_.get(index);
      }
      /**
       * <code>repeated string timeToRemind = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTimeToRemindBytes(int index) {
        return timeToRemind_.getByteString(index);
      }
      /**
       * <code>repeated string timeToRemind = 5;</code>
       */
      public Builder setTimeToRemind(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTimeToRemindIsMutable();
        timeToRemind_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string timeToRemind = 5;</code>
       */
      public Builder addTimeToRemind(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTimeToRemindIsMutable();
        timeToRemind_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string timeToRemind = 5;</code>
       */
      public Builder addAllTimeToRemind(
          java.lang.Iterable<java.lang.String> values) {
        ensureTimeToRemindIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, timeToRemind_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string timeToRemind = 5;</code>
       */
      public Builder clearTimeToRemind() {
        timeToRemind_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string timeToRemind = 5;</code>
       */
      public Builder addTimeToRemindBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTimeToRemindIsMutable();
        timeToRemind_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Organiser.Event)
    }

    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Organiser.Event)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Organiser_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Organiser_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Organiser.proto\022\tOrganiser\"Z\n\005Event\022\r\n" +
      "\005title\030\001 \003(\t\022\020\n\010dayMonth\030\002 \003(\t\022\014\n\004year\030\003" +
      " \003(\t\022\014\n\004time\030\004 \003(\t\022\024\n\014timeToRemind\030\005 \003(\t" +
      "B\025\n\010TextBaseB\tOrganiser"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Organiser_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Organiser_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Organiser_Event_descriptor,
        new java.lang.String[] { "Title", "DayMonth", "Year", "Time", "TimeToRemind", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
